name: Deploy Vite React App to S3

on:
  push:
    branches:
      - main # adjust if your main branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Sync dist folder to S3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_SECRET_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_SECRET_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.S3_SECRET_AWS_REGION }}
          SOURCE_DIR: dist
